config/routes.rb
Fruitback::Application.routes.draw do

  root to: "static_pages#home"
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  
  devise_for :users, controllers: {
    registrations: "registrations",
    confirmations: "confirmations",
    passwords: "passwords",
    sessions: "sessions" }
  
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  match '/profiles/check', to: 'profiles#check'
  match '/profiles/:id/confirm', to: 'profiles#confirm', as: :profiles_confirm
  match '/profiles/:id/upgrade', to: 'profiles#upgrade', as: :profiles_upgrade
  match '/customer_sites/:id/backup', to: 'customer_sites#backup', as: :backup
  
  resources :profiles
  
  resources :sites do
    resources :ideas do
      resources :comments
      resources :votes
    end
  end
  
  match '/customer_sites/:id/widget', to: 'customer_sites#widget'
  resources :customer_sites do
    resources :customer_ideas do
      resources :customer_comments
      resources :customer_responses
    end
  end
  
  resources :micro_sites do 
    resources :micro_ideas
  end
  
  

end

app/controllers/customer_ideas_controller.rb
class CustomerIdeasController < ApplicationController

  load_and_authorize_resource :idea, parent: false
  
  layout 'customer_site'
  
  # CUSTOMER VIEW
  
  def index
    prepare_index
  end
  
  def destroy
    @idea = Idea.find(params[:id])
    @site = @idea.site
    
    @idea.destroy
    
    flash[:notice] = "Idea was successfully deleted."
    redirect_to customer_site_customer_ideas_path(@site)
  end
  
  def show
    @idea = Idea.find(params[:id])
    @site = @idea.site
    redirect_to customer_site_customer_idea_customer_comments_path(@site, @idea)
  end
  
  protected
  
  def prepare_index
    @site = Site.find(params[:customer_site_id])
    @ideas = @site.ideas
    @ideas.sort! { |a, b| [b.votes.count, a.title] <=> [a.votes.count, b.title] }
  end
end

app/views/customer_ideas/index.html.haml
%p
  %i.icon-chevron-left
  = link_to "Back to my sites", customer_sites_path

%h1= @site.name

%h2 Ideas
- if @ideas.present?
  - @ideas.sort { |a, b| [b.votes.count, a.title] <=> [a.votes.count, b.title] }.each do |idea|
    %div.idea
      %a{ :href => customer_site_customer_idea_customer_comments_path(@site, idea) }
        = render 'ideas/small_idea', idea: idea
- else
  = render 'ideas/empty'

- content_for :sidebar do
  = render "customer_sites/sidebar"

app/views/customer_ideas/show.html.haml
%p
  %i.icon-chevron-left
  = link_to "Back to site", customer_site_path(@site)

= render 'ideas/idea', site: @site, idea: @idea, vote: @vote, url: customer_site_customer_idea_path(@site, @idea)

%h2 Comments
- if !@comments.empty?
  - @comments.each do |comment|
    = render 'comments/comment', comment: comment, url: customer_site_customer_idea_customer_comment_path(@site, @idea, comment)
- else
  = render 'comments/empty'

- content_for :sidebar do
  - if can? :create, @response
    %h3 Respond
    = render 'customer_responses/form', url: customer_site_customer_idea_customer_responses_path(@site, @idea)
    
  - if can? :create, @comment
    %h3 Add comment
    = render 'comments/form', url: customer_site_customer_idea_customer_comments_path(@site, @idea)
      
  = render 'customer_sites/sidebar'