config/routes.rb
Fruitback::Application.routes.draw do

  root to: "static_pages#home"
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  
  devise_for :users, controllers: {
    registrations: "registrations",
    confirmations: "confirmations",
    passwords: "passwords",
    sessions: "sessions" }
  
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  match '/profiles/check', to: 'profiles#check'
  match '/profiles/:id/confirm', to: 'profiles#confirm', as: :profiles_confirm
  match '/profiles/:id/upgrade', to: 'profiles#upgrade', as: :profiles_upgrade
  match '/customer_sites/:id/backup', to: 'customer_sites#backup', as: :backup
  
  resources :profiles
  
  resources :sites do
    resources :ideas do
      resources :comments
      resources :votes
    end
  end
  
  match '/customer_sites/:id/widget', to: 'customer_sites#widget'
  resources :customer_sites do
    resources :customer_ideas do
      resources :customer_comments
      resources :customer_responses
    end
  end
  
  resources :micro_sites do 
    resources :micro_ideas
  end
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text
  
  belongs_to :user
  attr_accessible :user_id
  
  belongs_to :idea
  attr_accessible :idea_id
  
  validates :text, presence: true, length: { maximum: 1000 }
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  load_and_authorize_resource
  
  # Show all comments of an idea
  def index
    prepare_index
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(params[:comment])

    # login through form
    if not login!
      prepare_index
      flash[:alert] = "Invalid email or password."
      render :index
      return
    end
    
    @comment.user = current_user
    @idea = Idea.find(params[:idea_id])
    @comment.idea_id = @idea.id
    @comment.save
    
    if @comment.errors.present?
      prepare_index
      render :index
      return
    end
    
    @site = @idea.site
    flash[:notice] = "Comment was successfully added."
    redirect_to site_idea_comments_path(@site, @idea)
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @idea = @comment.idea
    @site = @idea.site
    
    @comment.destroy
    
    respond_to do |format|
      format.html {
        if @comment.errors.present?
          prepare_index
          render :index
          return
        end
        
        flash[:notice] = "Comment was successfully deleted."
        redirect_to site_idea_comments_path(@site, @idea)
      }
      format.json { render json: { success: @comment.errors.blank? } }
    end
    
  end
  
  protected
  
  def prepare_index
    @idea = Idea.find(params[:idea_id])
    @site = @idea.site
    @comments = @idea.comments
    @responses = @idea.responses
    @vote = Vote.find_by_user_id_and_idea_id(current_user, @idea) if user_signed_in?
    @user = User.new
    @comments_url = site_idea_comments_path(@site, @idea)
  end
  
end

app/views/comments/_comment.html.haml
%div.well.posting{ id: "comment_#{comment.id}"}
  %p
    = comment.text
  
  %span.info
    Posted by #{link_to comment.user.name, profile_path(comment.user)}
    = distance_of_time_in_words(Time.now - comment.created_at)
    ago
  
  - if can? :destroy, comment
    = button_to "Delete", url, class: "btn btn-mini btn-danger delete ajax", method: :delete
  
  .clearfix

app/views/comments/_empty.html.haml
%div.well
  No comments yet. Be first to comment!

app/views/comments/_form.html.haml
= simple_form_for [@site, @idea, @comment], url: url do |f|
  = f.error_notification
  
  = f.input :text, required: true, as: :text, input_html: { rows: 3, class: "input-xlarge" }, placeholder: "Enter your comment here", label: false

  - if !user_signed_in?
    .check_email
      = simple_fields_for @user do |u|
        = u.input :email, input_html: { class: "input-xlarge" }, placeholder: "Your email address", label: false
        -#%div.input-prepend
        -#  %span.add-on
        -#    %i.icon-lock
        = u.input :password, input_html: { class: "input-xlarge" }, placeholder: "fruitback password", label: false
        = u.input :name, required: false, input_html: { class: "input-xlarge" }, placeholder: "Your name", label: false
  - else
    %p.info= "Logged in as #{current_user.name}"

  = f.button :submit, "Post comment", class: "btn btn-success"

app/views/comments/index.html.haml
%p
  %i.icon-chevron-left
  = link_to "Browse ideas", site_ideas_path(@site)

= render 'ideas/idea', site: @site, idea: @idea, vote: @vote, url: site_idea_path(@site, @idea)

- if !@responses.empty?
  %h2 Responses
  - @responses.each do |response|
    = render 'customer_responses/response', response: response, url: customer_site_customer_idea_customer_response_path(@site, @idea, response)

%h2 Comments
- if @comments.present?
  - @comments.each do |comment|
    = render 'comments/comment', comment: comment, url: site_idea_comment_path(@site, @idea, comment)
- else
  = render 'comments/empty'

- content_for :sidebar do
  - if can? :create, @comment
    %h3 Add comment
    = render 'comments/form', url: @comments_url
  = render 'sites/sidebar'