config/routes.rb
Fruitback::Application.routes.draw do

  root to: "static_pages#home"
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  
  devise_for :users, controllers: {
    registrations: "registrations",
    confirmations: "confirmations",
    passwords: "passwords",
    sessions: "sessions" }
  
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  match '/profiles/check', to: 'profiles#check'
  match '/profiles/:id/confirm', to: 'profiles#confirm', as: :profiles_confirm
  match '/profiles/:id/upgrade', to: 'profiles#upgrade', as: :profiles_upgrade
  match '/customer_sites/:id/backup', to: 'customer_sites#backup', as: :backup
  
  resources :profiles
  
  resources :sites do
    resources :ideas do
      resources :comments
      resources :votes
    end
  end
  
  match '/customer_sites/:id/widget', to: 'customer_sites#widget'
  resources :customer_sites do
    resources :customer_ideas do
      resources :customer_comments
      resources :customer_responses
    end
  end
  
  resources :micro_sites do 
    resources :micro_ideas
  end
  
  

end

app/controllers/customer_comments_controller.rb
class CustomerCommentsController < ApplicationController

  load_and_authorize_resource :comment, parent: false
  
  layout 'customer_site'
  
  # Show all comments of an idea
  def index
    prepare_index
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(params[:comment])
    
    # login through form
    if not login!
      prepare_index
      flash[:alert] = "Invalid email or password."
      render :index
      return
    end
    
    @comment.user = current_user
    @idea = Idea.find(params[:customer_idea_id])
    @comment.idea_id = @idea.id
    @comment.save
    
    if @comment.errors.present?
      prepare_index
      render :index
      return
    end
    
    @site = @idea.site
    flash[:notice] = "Comment was successfully added."
    redirect_to customer_site_customer_idea_customer_comments_path(@site, @idea)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @idea = @comment.idea
    @site = @idea.site
    
    @comment.destroy
    
    respond_to do |format|
      format.html {
        if @comment.errors.present?
          prepare_index
          render :index
          return
        end
        
        flash[:notice] = "Comment was successfully deleted."
        redirect_to customer_site_customer_idea_customer_comments_path(@site, @idea)
      }
      format.json { render json: { success: @comment.errors.blank? } }
    end
  end
  
  protected
  
  def prepare_index
    @idea = Idea.find(params[:customer_idea_id])
    @site = @idea.site
    @comments = @idea.comments
    @responses = @idea.responses
    @vote = Vote.find_by_user_id_and_idea_id(current_user, @idea) if user_signed_in?
    @user = User.new
    @response = Response.new
    @comments_url = customer_site_customer_idea_customer_comments_path(@site, @idea)
  end
  
end

app/views/customer_comments/index.html.haml
%p
  %i.icon-chevron-left
  = link_to "Back to ideas", customer_site_customer_ideas_path(@site)

= render 'ideas/idea', site: @site, idea: @idea, vote: @vote, url: customer_site_customer_idea_path(@site, @idea)

- if !@responses.empty?
  %h2 Responses
  - @responses.each do |response|
    = render 'customer_responses/response', response: response, url: customer_site_customer_idea_customer_response_path(@site, @idea, response)
/TODO deletion

%h2 Comments
- if !@comments.empty?
  - @comments.each do |comment|
    = render 'comments/comment', comment: comment, url: customer_site_customer_idea_customer_comment_path(@site, @idea, comment)
- else
  = render 'comments/empty'

- content_for :sidebar do
  - if can? :create, @response
    %h3 Respond
    = render 'customer_responses/form', url: customer_site_customer_idea_customer_responses_path(@site, @idea)
    
  - if can? :create, @comment
    %h3 Add comment
    = render 'comments/form', url: customer_site_customer_idea_customer_comments_path(@site, @idea)
      
  = render 'customer_sites/sidebar'