config/routes.rb
Fruitback::Application.routes.draw do

  root to: "static_pages#home"
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  
  devise_for :users, controllers: {
    registrations: "registrations",
    confirmations: "confirmations",
    passwords: "passwords",
    sessions: "sessions" }
  
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  match '/profiles/check', to: 'profiles#check'
  match '/profiles/:id/confirm', to: 'profiles#confirm', as: :profiles_confirm
  match '/profiles/:id/upgrade', to: 'profiles#upgrade', as: :profiles_upgrade
  match '/customer_sites/:id/backup', to: 'customer_sites#backup', as: :backup
  
  resources :profiles
  
  resources :sites do
    resources :ideas do
      resources :comments
      resources :votes
    end
  end
  
  match '/customer_sites/:id/widget', to: 'customer_sites#widget'
  resources :customer_sites do
    resources :customer_ideas do
      resources :customer_comments
      resources :customer_responses
    end
  end
  
  resources :micro_sites do 
    resources :micro_ideas
  end
  
  

end

app/controllers/customer_sites_controller.rb
class CustomerSitesController < ApplicationController
  
  load_and_authorize_resource :site, parent: false, except: :widget
  
  layout 'customer_site'
  
  # CUSTOMER VIEW
  
  def index
    prepare_index
    @site = Site.new
  end
  
  def create
    @site = Site.new(params[:site])
    @site.user = current_user
    @site.save
    
    if @site.errors.present?
      prepare_index
      render :index
      return
    end
    
    flash[:notice] = "Site was successfully registered."
    redirect_to customer_site_customer_ideas_path(@site)
  end
  
  def edit
    @site = Site.find(params[:id])
    @site_url = customer_site_path(@site)
  end
  
  def update
    @site = Site.find(params[:id])
    @site.update_attributes(params[:site])
    @site.save
    
    if @site.errors.present?
      @site_url = customer_site_path(@site)
      render :edit
      return
    end
    
    flash[:notice] = "Site was successfully updated."
    redirect_to edit_customer_site_path(@site)
  end
  
  def show
    @site = Site.find(params[:id])
    redirect_to customer_site_customer_ideas_path(@site)
  end
  
  def widget
    @site = Site.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
  
  def backup
    @site = Site.find(params[:id])
    
    votes = { votes: { include: :user } }
    comments = { comments: { include: :user } }
    responses = { responses: { include: :user } }
    
    data = render_to_string json: @site.as_json(
      include: { ideas: { include: [ 
          :user,
          votes, 
          comments,
          responses, 
        ] } } )
        
    send_data data, type: "text/json",filename: "backup.json"
  end
  
  protected
  
  def prepare_index
    @sites = if admin?
      Site.all
    elsif user_signed_in?
      current_user.sites
    else
      []
    end
    @sites_url = customer_sites_path
  end
  
end

app/helpers/customer_sites_helper.rb
module CustomerSitesHelper

  def widget_url(site)
    s = root_url
    s.slice! /https?:\/\//
    "#{s}customer_sites/#{site.id}/widget.js"
  end

end

app/views/customer_sites/_form.html.haml
= simple_form_for @site, url: url do |f|
  = f.error_notification
  
  = f.input :name, placeholder: "Your site's name", required: true
  = f.input :url, placeholder: "Your site's url"

  = f.button :submit, class: 'btn btn-success'

app/views/customer_sites/_sidebar.html.haml
%p
  %i.icon-eye-open
  = link_to "See this site as a visitor", site_path(@site), target: "_blank"
%p
  %i.icon-pencil
  = link_to "Settings", edit_customer_site_path(@site)
%p
  %i.icon-download-alt
  = link_to "Export site backup (json)", backup_path(@site)

app/views/customer_sites/edit.html.haml
%p
  %i.icon-chevron-left
  = link_to "Back to the site", customer_site_customer_ideas_path(@site)

%h1
  Settings for:
  =@site.name

%h2 Change site
= render 'form', url: @site_url

%h2 Insert this to your homepage
%textarea.code.input-xxlarge{rows: "7", onClick: "this.select();"}
  &  <script type="text/javascript">
  &    (function() {
  &      var frb = document.createElement('script'); frb.type = 'text/javascript'; frb.async = true;
  &      frb.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + '#{widget_url(@site)}';
  &      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(frb, s);
  &    })();
  &  </script>

- content_for :sidebar do
  = render "sidebar"

app/views/customer_sites/index.html.haml
%h1 Sites

- if @sites.present?
  %table.table.table-hover.table-bordered
    %tbody
      - @sites.each do |site|
        %tr
          %td= link_to site.name, customer_site_customer_ideas_path(site)
- else
  %div.well
    %h2 First steps
    You don't have created any sites yet. Take a look on the sidebar on the right and create your first site right now!

- content_for :sidebar do
  - if can? :create, @site
    %h2 Create new site
    = render 'form', url: @sites_url

app/views/customer_sites/widget.js.erb
<% #button_position = "left: -10px; top: 40%;" %> 
<% color = "FAE117" %> 
var button_css = "<%= (render partial: 'widgets/button_css', locals: { position: button_position(7), color: color } ).delete("\n") %>";
var iframe_css = "<%= (render 'widgets/iframe_css').delete("\n") %>";
var html_button = "<img src=\"<%= logo_url %>\" style=\"margin-top: -20px; margin-left: 5px;\">";
var html_iframe = "<%= (render partial: 'widgets/iframe.html', locals: { site: @site, color: color } ).delete("\n").html_safe %>";

var button = 'button';
var fruitback = 'fruitback';

//feedback button
var fbDivButton = document.createElement('div');
fbDivButton.setAttribute('id', button);
fbDivButton.setAttribute('style', button_css);
fbDivButton.setAttribute('onClick', 'javascript:showIFrame();');
fbDivButton.innerHTML = html_button;

//feedback widget
var fbDivFrame = document.createElement('div');
fbDivFrame.setAttribute('id', fruitback);
fbDivFrame.setAttribute('style', iframe_css);
fbDivFrame.setAttribute('onClick', 'javascript:hideIFrame();');
fbDivFrame.innerHTML = html_iframe;

var bodyTag = document.getElementsByTagName('body');
bodyTag[0].appendChild(fbDivButton);
bodyTag[0].appendChild(fbDivFrame);

var showIFrame = function() {
	document.getElementById(fruitback).style.display = 'block';
}

var hideIFrame = function() {
	document.getElementById(fruitback).style.display = 'none';
}